#!/bin/bash
#protoc authservice.proto -I=. --cpp_out=.
#protoc connect_server.proto -I=. --cpp_out=.
#protoc peer_server.proto -I=. --cpp_out=.
#protoc push_server.proto -I=. --cpp_out=.
#protoc ServicePacket.proto -I=. --cpp_out=.

rm -f *.h
rm -f *.cc
for protofile in 'ls'
do
	protoc $protofile -I=. --cpp_out=.
done;
